language: ruby
rvm:
  - 1.9.3
  
env:
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake spec
  - karma start --single-run

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database angular_rails_travis_ci_test' -U postgres
  - npm install -g grunt-cli
  - cd angular
  - npm install
  - bower install
  - cd ..
  